// <auto-generated />
using System;
using Ludus_Stadium.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Ludus_Stadium.Migrations
{
    [DbContext(typeof(ludusstadiumsContext))]
    [Migration("20230508025944_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_0900_ai_ci")
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");

            modelBuilder.Entity("Ludus_Stadium.Models.stadium", b =>
                {
                    b.Property<int>("id")
                        .HasColumnType("int");

                    b.Property<string>("adress")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("capacity")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.Property<DateTime>("openingDate")
                        .HasColumnType("datetime");

                    b.HasKey("id");

                    b.ToTable("stadium", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
