# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - ludusstadiums

on:
  push:
    branches:
      - production
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://ludusapicontainer.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_92d995e8648146a697c3673a49cb3e51 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_401933f418934b408bcb467185d28514 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: ludusapicontainer.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_92d995e8648146a697c3673a49cb3e51 }}/ludus_service_stadiums:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'ludusstadiums'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_37ea7fc6d760461196a87b5dbe6c3105 }}
        images: 'ludusapicontainer.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_92d995e8648146a697c3673a49cb3e51 }}/ludus_service_stadiums:${{ github.sha }}'